### ISSUE TITLE
Project Creation

### ISSUE THREAD

**Issue by AshleyCheyemi** [emory-libraries-ecds/ATLMaps-Ember#4]
-- Edit description box will not collapse with either Save or Close; rather, must click outside description box to return to maps
-- What does the Publish selection box in the description of project box mean?
-- Video and Photo...upload? Or insert link?
-- Remove button on map layers not always available (see Buford Maps project)
-- Other than clicking on Projects on top bar, how to access project once saved? How to see multiple saved projects and then select one to view? 
-- Can we create a link to share projects (vs. making them public)?
-- “Buford Maps” automatically loaded to Public Projects, even though it is supposed to be my private project

**Comment by jayvarner** [comment]
@AshleyCheyemi, thanks for all of these. Some of them I knew about but kept forgetting. It's really helpful to have a list here.

- _Edit description box will not collapse with either Save or Close; rather, must click outside description box to return to maps_

In the next code push, `Save` saves the description and exits the edit mode. The `Cancel` button now exits edit mode and rolls back any changes.

- _What does the Publish selection box in the description of project box mean?_

Wording could be better. If a project is `published` it can be seen by anyone with the link. A project that is `featured` will show up on the homepage and on the projects page. Maybe, as you suggest in another question, something like `Share Project` button that. On the backend, it will mark the project as `published`. On the front end, it provides a link?

- _Video and Photo...upload? Or insert link?_

Link. and only Youtube is currently supported. This needs a lot of work.

- _Remove button on map layers not always available (see Buford Maps project)_

It will only show if you are logged in.

- _Other than clicking on Projects on top bar, how to access project once saved? How to see multiple saved projects and then select one to view?_

The projects page could be organized better. Other than that, and the home page, what would you expect/like to see?

- _Can we create a link to share projects (vs. making them public)?_
Previous and next response.

_"Buford Maps" automatically loaded to Public Projects, even though it is supposed to be my private project_

I'm aware of this bug. In short, the projects are not viewable to everyone. I can not see the "Buford Maps" project. It's fixed in the next code push.

Long answer is the backend only returns featured projects. If you are not logged in, the server will only return featured projects. However, if you are logged in, your projects are also loaded into the local store, so they show up when all projects are listed. Fixing it is a matter of adding a filter on that section and will be in the next code push.

**Comment by jayvarner** [comment]
Remaining work is to add help text defining "Publish"...or change to "Share". We should look at what language Google Docs, Dropbox, etc use.

**Comment by jayvarner** [comment]
@ewilloughby the relevant code is here: [https://github.com/ecds/ATLMaps-Client/blob/develop/app/templates/project/settings.hbs#L10](https://github.com/ecds/ATLMaps-Client/blob/develop/app/templates/project/settings.hbs#L10)

For the tooltip, let's look at using something like [ember-tooltips](https://github.com/sir-dunxalot/ember-tooltips).

**Comment by ewilloughby** [comment]
Added a hover tooltip for "Publish" using ember-tooltips to clarify what this checkbox does.
![image](https://user-images.githubusercontent.com/4126936/30136989-47edd418-932f-11e7-923b-3fb8d37f7da5.png)



aaaf7e0
